services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: population_app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.3
    container_name: population_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "33060:3306"
    volumes:
      - ./world.sql:/docker-entrypoint-initdb.d/world.sql
